name: Basic checks
on:
  push:
  pull_request:

env:
  POETRY_VERSION: 1.3.2

jobs:

  BasicChecks:
    name: Basic checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip==23.0
            pip install poetry==${{ env.POETRY_VERSION }}
            poetry config virtualenvs.create false --local
            poetry install

      - name: Lint with flake8
        run: |
          flake8 coffee_db --max-line-length 120